import 'dotenv/config';

const {
  NODE_ENV,
  DEV_DATABASE_USER,
  DEV_DATABASE_PASSWORD,
  DEV_DATABASE_HOST,
  DEV_DATABASE_NAME,
  DEV_DATABASE_PORT,
  DEV_DATABASE_MAX_CONNECTIONS,
  DEV_PAPERTRAIL_PORT,
  DEV_PAPERTRAIL_HOST,
  DEV_DEBUG,
  DEV_PORT,
  DEV_DATABASE_STRING,
} = process.env;

export default {
  NODE_ENV: NODE_ENV,
  DEBUG: DEV_DEBUG,
  DATABASE_USER: DEV_DATABASE_USER,
  DATABASE_PASSWORD: DEV_DATABASE_PASSWORD,
  DATABASE_HOST: DEV_DATABASE_HOST,
  DATABASE_NAME: DEV_DATABASE_NAME,
  DATABASE_PORT: DEV_DATABASE_PORT,
  DATABASE_MAX_CONNECTIONS: DEV_DATABASE_MAX_CONNECTIONS,
  PAPERTRAIL_PORT: DEV_PAPERTRAIL_PORT,
  PAPERTRAIL_HOST: DEV_PAPERTRAIL_HOST,
  PORT: DEV_PORT,
  DATABASE_URL: DEV_DATABASE_STRING,
};
