import 'dotenv/config';

const {
  NODE_ENV,
  PROD_DATABASE_USER,
  PROD_DATABASE_PASSWORD,
  PROD_DATABASE_HOST,
  PROD_DATABASE_NAME,
  PROD_DATABASE_PORT,
  PROD_DATABASE_MAX_CONNECTIONS,
  PROD_PAPERTRAIL_PORT,
  PROD_PAPERTRAIL_HOST,
  PROD_DEBUG,
  PROD_PORT,
  PROD_DATABASE_STRING,
} = process.env;

export default {
  NODE_ENV: NODE_ENV,
  DEBUG: PROD_DEBUG,
  DATABASE_USER: PROD_DATABASE_USER,
  DATABASE_PASSWORD: PROD_DATABASE_PASSWORD,
  DATABASE_HOST: PROD_DATABASE_HOST,
  DATABASE_NAME: PROD_DATABASE_NAME,
  DATABASE_PORT: PROD_DATABASE_PORT,
  DATABASE_MAX_CONNECTIONS: PROD_DATABASE_MAX_CONNECTIONS,
  PAPERTRAIL_PORT: PROD_PAPERTRAIL_PORT,
  PAPERTRAIL_HOST: PROD_PAPERTRAIL_HOST,
  PORT: PROD_PORT,
  DATABASE_URL: PROD_DATABASE_STRING,
};
